before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: P5UkPaKpw9oGDVU6QAwsgwJ2JTad8l1pv+2+gnt2dFyTy/j3dkmpmUAKdiDSlNTKq47ZfczkSuHn1qcGNkj/1Fo9BUYVQuJZkjVbQWSi3yz5ceOH6KX4q27Zu2yYu9ha8eh1Kzf9sJ6T2+X5dD3U3c+6DYRViAydxyZrIY0dErRGQIHZ2CrxFkiIgvJibbYDqPOzSrVPhar9JQII1gkbnz7WiCgUFDHlXl2QWn4Hpaq+k56f1+XeyCB7UXPsHbpplZ72YIi+H26PFzXypkBQ0TGRvKb+T7UcLaCWDPCTt11AMMxcbO7d2lVwoEegrBdzfkNBdBf3KEc+87wVmzxCdVkCTD0YoOAjLQNyeyJZ4+i7GoUnE6WKwLQFt2qQCoGiWLI3LpDlT64p/r6Rw9kOUk+ZcjtFMSW0CdOnnQzMAyLmjJzKGuv+r8eNSgsxzs+B2p0NCR5ADEm6HFKoKjkf66Vi5VQJcCe4W6q5n1+M5sl7+sx9HSRAuxOyTqNtwvmhaZu99UoKD+VDmMl0v7w3G8Ej+P/MHNdVVVJW6jmkDsigbIdJIiagEgCZI7kNEIh9fhAVncdafIOUqjpabR/S7zD6R2QEh9Hx9nRvduwTrAonGJbsgh5dMvWcD/GsRbJqlqUg3kTdswRLs8NQwmPm1OZUnA0hSLjPAr7S8fnwYjU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
